# Generated by Django 4.0.2 on 2022-02-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_backend', '0002_board_card_cardlabel_cardlist_cardmember_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cardlabel',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cardlist',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cardmember',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='workspacemember',
            old_name='modified_date',
            new_name='updated_at',
        ),
    ]
