version: '3.7'
services:
  db:
    image: mysql:8.0.28
    restart: always
    command: |
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello
  app:
    build: .
    ports:
      - "5003:8000"
    restart: always
    env_file:
      - .env.example
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db